DAYS = day1_part1 day1_part2 \
       day2_part1 day2_part2 \
       day3_part1 day3_part2 \
       day4_part1 day4_part2 \
       day5_part1 day5_part2 \
       day6_part1 day6_part2 \
       day7_part1 day7_part2 \
       day8_part1 day8_part2
all: $(DAYS)

day1_part1:
	@opam exec coretop day1_part1.ml

day1_part2:
	@opam exec coretop day1_part2.ml

day2_part1:
	@opam exec coretop day2_part1.ml

day2_part2:
	@opam exec coretop day2_part2.ml

day3_part1:
	@opam exec coretop day3_part1.ml

day3_part2:
	@opam exec coretop day3_part2.ml

day4_part1:
	@opam exec coretop day4_part1.ml

day4_part2:
	@opam exec coretop day4_part2.ml

day5_part1:
	@opam exec coretop day5_part1.ml

day5_part2:
	@opam exec coretop day5_part2.ml

day6_part1:
	@opam exec coretop day6_part1.ml

day6_part2:
	@opam exec coretop day6_part2.ml

day7_part1:
	@opam exec coretop day7_part1.ml

day7_part2:
	@opam exec coretop day7_part2.ml

day8_part1:
	@opam exec coretop day8_part1.ml

day8_part2:
	@opam exec coretop day8_part2.ml
